/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tarea2;

import Domain.Vehicule;
import File.RamdonAccessFile;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author hansel
 */
public class InsertCar extends javax.swing.JInternalFrame {

    /**
     * Creates new form InsertCar
     */
    public InsertCar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNameCar = new javax.swing.JLabel();
        jAnnoCar = new javax.swing.JLabel();
        jKmCar = new javax.swing.JLabel();
        jAmericanCar = new javax.swing.JLabel();
        jSerieCar = new javax.swing.JLabel();
        txtNameCar = new javax.swing.JTextField();
        txtAnnoCar = new javax.swing.JTextField();
        txtKmCar = new javax.swing.JTextField();
        txtAmericano = new javax.swing.JTextField();
        txtSerieCar = new javax.swing.JTextField();
        jbInsertar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Insertar Vehiculos");

        jNameCar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jNameCar.setText("Nombre");

        jAnnoCar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jAnnoCar.setText("Año");

        jKmCar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jKmCar.setText("kilometraje");

        jAmericanCar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jAmericanCar.setText("País");

        jSerieCar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jSerieCar.setText("# Serie");

        txtNameCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameCarActionPerformed(evt);
            }
        });

        txtAnnoCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnnoCarActionPerformed(evt);
            }
        });

        jbInsertar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbInsertar.setText("Insertar");
        jbInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInsertarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSerieCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jAmericanCar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jKmCar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jAnnoCar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jNameCar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNameCar)
                            .addComponent(txtAnnoCar)
                            .addComponent(txtKmCar)
                            .addComponent(txtAmericano)
                            .addComponent(txtSerieCar, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jbInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNameCar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNameCar, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAnnoCar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnnoCar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jKmCar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKmCar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAmericano, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jAmericanCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSerieCar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSerieCar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameCarActionPerformed

    private void jbInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInsertarActionPerformed
        // TODO add your handling code here:
        String nameCar = txtNameCar.getText().trim();
        if (nameCar.isEmpty()) {
            JOptionPane.showMessageDialog(this, "¡No se ingreso el nombre del vehiculo!", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String annoCar = txtAnnoCar.getText().trim();
        if (annoCar.isEmpty()) {
            JOptionPane.showMessageDialog(this, "¡No se ingreso el año del vehiculo!", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int numberAnno;
        try {
            numberAnno = Integer.parseInt(annoCar);
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un número entero para el año.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String kmCar = txtAnnoCar.getText().trim();
        if (kmCar.isEmpty()) {
            JOptionPane.showMessageDialog(this, "¡No se ingreso el kilometraje del vehiculo!", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int numberKmCar;
        try {
            numberKmCar = Integer.parseInt(kmCar);
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el kilometraje en numeros.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String countryCar = txtAmericano.getText().trim();
        if (countryCar.isEmpty()) {
            JOptionPane.showMessageDialog(this, "¡No se ingreso el pais de origen!", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String serieCar = txtSerieCar.getText().trim();
        if (serieCar.isEmpty()) {
            JOptionPane.showMessageDialog(this, "¡No se ingreso la serie del vehiculo!", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int numberSerie;
        try {
            numberSerie = Integer.parseInt(serieCar);
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un número entero para la serie.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            RamdonAccessFile.start(new File("vehiculo.dad"));
            RamdonAccessFile.addVehicule(new Vehicule(nameCar, numberAnno, numberKmCar, countryCar, numberSerie, true));
            RamdonAccessFile.close();
            JOptionPane.showMessageDialog(this, "El registro se realizó correctamente.", "Notificación", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error en la escritura de datos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        this.txtNameCar.setText(null);
        this.txtAnnoCar.setText(null);
        this.txtKmCar.setText(null);
        this.txtAmericano.setText(null);
        this.txtSerieCar.setText(null);
    }//GEN-LAST:event_jbInsertarActionPerformed

    private void txtAnnoCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnnoCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnnoCarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAmericanCar;
    private javax.swing.JLabel jAnnoCar;
    private javax.swing.JLabel jKmCar;
    private javax.swing.JLabel jNameCar;
    private javax.swing.JLabel jSerieCar;
    private javax.swing.JButton jbInsertar;
    private javax.swing.JTextField txtAmericano;
    private javax.swing.JTextField txtAnnoCar;
    private javax.swing.JTextField txtKmCar;
    private javax.swing.JTextField txtNameCar;
    private javax.swing.JTextField txtSerieCar;
    // End of variables declaration//GEN-END:variables
}
